### ISSUE TITLE
oa_fetch search issue?

### ISSUE THREAD

**Issue by yhan818** [ropensci/openalexR#196]
Please see https://openalex.org/authors/a5019422724 

It shows that this person has affiliations with "University of Arizona", "Integrative Medicine Institute",   "Arizona Pain Specialists", "Thrive", and "Cancer Teatment Centers of America". 

When I run 
`author_from_names <- oa_fetch(entity = "author", search = "Lise Alschuler") `

 The returned df has only one affiiation_display_name = "Integrated Medicine Institute". So where are other affiliation data?

**Comment by trangdata** [comment]
Thanks for reporting this @yhan818. OpenAlex used to only give one most recent affiliation. This must be a new change. I'm currently on maternity leave but perhaps @yjunechoe or @massimoaria can take a look! 🙏🏽

**Comment by yjunechoe** [comment]
Thanks for the issue! I'm still thinking through the best way to handle this. For backwards compatibility, I think it'd be safest to introduce a new column like `affiliations_other` which records the institution IDs of the author's previous affiliations. I'm hesitant to add more info about the other affiliations than the IDs to our already crowded output, but may be convinced otherwise.

Proposal tracked in #199

**Comment by yjunechoe** [comment]
Hi @yhan818 - could you comment on whether #199 resolves the issue for your usecase? Let us know if you have any concerns/suggestions!

**Comment by yhan818** [comment]
Will do .

**Comment by yhan818** [comment]
It works. 

Note: affiliations_other can return a string or a vector of strings.  For example:
1. affiliations_other returns a string
author_name <- "Tejo K Vemulapalli"
affiliation_name <- "University of Arizona"
author_from_names <- oa_fetch(entity = "author", search = author_name)

2. affiliations_other return a vector of strings
author_name <- "Lise Alschuler"  
affiliation_name <- "University of Arizona"
author_from_names <- oa_fetch(entity = "author", search = author_name)


So both cases shall be taken care of when handling this affiliation data.
