### ISSUE TITLE
oa2df fails to convert list to df

### ISSUE THREAD

**Issue by peetmate** [ropensci/openalexR#232]
Hi,

I think this should repeatable:
https://github.com/CIAT/ERA_dev/blob/main/R/search/livestock_2024/search_terms.R

Running search i=4 (line 247:249)

oa2df fails to convert list created by oa_request to df

This is the error received:
```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 3, 0
```

**Comment by janpht** [comment]
Hi there,

I have the same "differing number of rows"-issue, if running the following with oa_fetch:

```
library (openalexR)
library (tidyverse)

books <- oa_fetch(
  entity = "works", 
  from_publication_date = "2020-01-01",
  to_publication_date = "2023-12-31",
  type = "book",
  verbose = TRUE
)
```

**Comment by mariusbommert** [comment]
Hi,

I got a similar error message and it seems to be a problem with raw_affiliation_string in my case. 

```
query <- oa_query(
  identifier = "https://openalex.org/W3081691125",
  entity = "works",
  endpoint = "https://api.openalex.org"
)

res <- oa_request(
  query_url = query2,
  count_only = FALSE,
  verbose = FALSE
)

oa2df(res, entity = "works")
```

leads to 
```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
```

I analysed the error and found out that the problem seems to occur in https://github.com/ropensci/openalexR/blob/main/R/oa2df.R line 229 or the rbind of this part if the raw_affiliation_string is empty.  In my fork of this repo https://github.com/mariusbommert/openalexR/blob/main/R/oa2df.R line 244 I used 
```
 au_affiliation_raw <- unlist(replace_w_na(l$raw_affiliation_strings[1]))
 ```
 instead which seems to fix the problem. Maybe the problem arised due to OpenAlex deprecating raw_affiliation_string and using raw_affiliation_strings instead, see https://docs.openalex.org/api-entities/works/work-object/authorship-object. 
 
In my fork of this repo I added options to get more than one institution and raw_affiliation_string per author. This is why I have a different number of lines of code.

**Comment by janpht** [comment]
What a response time! Thank you very much, it works well.

**Comment by trangdata** [comment]
> I analysed the error and found out that the problem seems to occur [...] if the raw_affiliation_string is empty.

Thanks a lot @mariusbommert for investigating the issue. You're right, I needed to consider the NULL case for raw_affiliation_string. Fixed in #233.

**Comment by peetmate** [comment]
many thanks for reviewing this issue

**Comment by manubrucco** [comment]
Hello there! When I apply the solution proposed by mariusbommert, an error occurs

_Error in empty_list(inst_cols) : could not find function "empty_list"_

Thank you in advance for any help you can provide!

**Comment by trangdata** [comment]
Hi @manubrucco could you re-install the package and try again? 🙏🏽 

``` r
install.packages("openalexR")
```

**Comment by manubrucco** [comment]
@trangdata Thank you!! I'd updated the package before and did work, but now that I uninstalled it and installed again it worked!!
