### ISSUE TITLE
Feature Request: Do snowball search also from DOI and not only from works id

### ISSUE THREAD

**Issue by rkrug** [ropensci/openalexR#259]
I am regularly doing snowball searches bed on DOIs. 

For this I have to

1. fetch the ids from the key papers DOIs
2. do the snowball search (`oa_snowball)`) 

It would be great, if I could do the snowball search directly with the DOIs.

Cheers

Rainer

**Comment by yjunechoe** [comment]
This was added as part of https://github.com/ropensci/openalexR/pull/26! - though it's been a while since it happened and it wasn't loudly advertised then.

@trangdata perhaps we could promote one of the tests you wrote for this behavior into examples?

https://github.com/ropensci/openalexR/blob/44a5287007c88a9d13549d585307cc8077fa367e/tests/testthat/test-oa_snowball.R#L42-L49

**Comment by rkrug** [comment]
Oh - this is not refute ind the help file https://github.com/ropensci/openalexR/blob/44a5287007c88a9d13549d585307cc8077fa367e/R/oa_snowball.R#L3C30-L3C63

There it still says `vector of openalex identifiers`.

Thanks.

**Comment by trangdata** [comment]
> perhaps we could promote one of the tests you wrote for this behavior into examples?

That's a good idea!
